In [8]:
import pandas as pd
import pickle

In [9]:
with open('data/dane_ola.pkl', 'rb') as file:
    data_ola = pickle.load(file)

with open('data/dane_maciek.pkl', 'rb') as file:
    data_maciek = pickle.load(file)

In [10]:
data = data_ola
data['ts_date'] = pd.to_datetime(data['ts_date'])

In [111]:
data

,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,spotify_episode_uri,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,ts_date,ts_time
0,"iOS 15.4.1 (iPad13,1)",8192,PL,Prisoner (feat. Dua Lipa),Miley Cyrus,Plastic Hearts,spotify:track:2Oycxb8QbPkpHTo8ZrmG0B,None,None,None,...,NaN,clickrow,endplay,False,False,0.0,NaN,False,2022-06-05,16:54:47
1,"iOS 15.4.1 (iPad13,1)",258969,PL,Ribs,Lorde,Pure Heroine,spotify:track:2MvvoeRt8NcOXWESkxWn3g,None,None,None,...,NaN,clickrow,trackdone,False,False,0.0,NaN,False,2022-06-05,16:59:05
2,"iOS 15.4.1 (iPad13,1)",187988,PL,Blue,Jome,Blue,spotify:track:3GaEQmo4RDdK80kszdNZN1,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-06-05,17:02:13
3,"iOS 15.4.1 (iPad13,1)",229173,PL,Atlantis,Seafret,Tell Me It's Real,spotify:track:1Fid2jjqsHViMX6xNH70hE,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-06-05,17:06:03
4,"iOS 15.4.1 (iPad13,1)",191106,PL,skins,The Haunting,skins,spotify:track:6Q2kn3CDlYFNwS8CAc4YzB,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-06-05,17:09:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378940,"iOS 15.2.1 (iPhone13,2)",230426,PL,Dirty Harry,Gorillaz,Demon Days,spotify:track:2bfGNzdiRa1jXZRdfssSzR,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:09:28
378941,"iOS 15.2.1 (iPhone13,2)",248493,PL,Kansas,Gorillaz,The Now Now,spotify:track:7FJ7lHtpbWvPKe3zCoeAWC,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:13:37
378942,"iOS 15.2.1 (iPhone13,2)",340920,PL,Clint Eastwood,Gorillaz,Gorillaz,spotify:track:1RKUoGiLEbcXN4GY4spQDx,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:19:19
378943,"iOS 15.2.1 (iPhone13,2)",272666,PL,Strobelite (feat. Peven Everett),Gorillaz,Humanz,spotify:track:6XGddj522FQRHXEhBtjiJu,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:23:52
378944,"iOS 15.2.1 (iPhone13,2)",274760,PL,Souk Eye,Gorillaz,The Now Now,spotify:track:4fjzDf54eBNOlW45mNe14U,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:28:27

In [112]:
df = data[data['ts_date'].dt.year == 2022].copy()
df.groupby(['master_metadata_track_name', 'master_metadata_album_artist_name']).size().reset_index(
        name='counts').sort_values(by='counts', ascending=False)
df[['master_metadata_track_name', 'master_metadata_album_artist_name']].head(10)

  master_metadata_track_name master_metadata_album_artist_name
0  Prisoner (feat. Dua Lipa)                       Miley Cyrus
1                       Ribs                             Lorde
2                       Blue                              Jome
3                   Atlantis                           Seafret
4                      skins                      The Haunting
5                  luv story                             Zekey
6    Les incertains anonymes              Violette fleur bleue
7                    ミラーチューン                          ZUTOMAYO
8                       Sony                         VHS LOGOS
9                 Beach Walk                       Whitewoods

In [113]:
df = data[data['ts_date'].dt.year == 2022].copy()
df = df.groupby([ 'master_metadata_album_artist_name']).size().reset_index()
df.shape[0]

4029

In [114]:
data

,platform,ms_played,conn_country,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,episode_name,episode_show_name,spotify_episode_uri,...,audiobook_chapter_title,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode,ts_date,ts_time
0,"iOS 15.4.1 (iPad13,1)",8192,PL,Prisoner (feat. Dua Lipa),Miley Cyrus,Plastic Hearts,spotify:track:2Oycxb8QbPkpHTo8ZrmG0B,None,None,None,...,NaN,clickrow,endplay,False,False,0.0,NaN,False,2022-06-05,16:54:47
1,"iOS 15.4.1 (iPad13,1)",258969,PL,Ribs,Lorde,Pure Heroine,spotify:track:2MvvoeRt8NcOXWESkxWn3g,None,None,None,...,NaN,clickrow,trackdone,False,False,0.0,NaN,False,2022-06-05,16:59:05
2,"iOS 15.4.1 (iPad13,1)",187988,PL,Blue,Jome,Blue,spotify:track:3GaEQmo4RDdK80kszdNZN1,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-06-05,17:02:13
3,"iOS 15.4.1 (iPad13,1)",229173,PL,Atlantis,Seafret,Tell Me It's Real,spotify:track:1Fid2jjqsHViMX6xNH70hE,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-06-05,17:06:03
4,"iOS 15.4.1 (iPad13,1)",191106,PL,skins,The Haunting,skins,spotify:track:6Q2kn3CDlYFNwS8CAc4YzB,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-06-05,17:09:15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378940,"iOS 15.2.1 (iPhone13,2)",230426,PL,Dirty Harry,Gorillaz,Demon Days,spotify:track:2bfGNzdiRa1jXZRdfssSzR,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:09:28
378941,"iOS 15.2.1 (iPhone13,2)",248493,PL,Kansas,Gorillaz,The Now Now,spotify:track:7FJ7lHtpbWvPKe3zCoeAWC,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:13:37
378942,"iOS 15.2.1 (iPhone13,2)",340920,PL,Clint Eastwood,Gorillaz,Gorillaz,spotify:track:1RKUoGiLEbcXN4GY4spQDx,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:19:19
378943,"iOS 15.2.1 (iPhone13,2)",272666,PL,Strobelite (feat. Peven Everett),Gorillaz,Humanz,spotify:track:6XGddj522FQRHXEhBtjiJu,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:23:52
378944,"iOS 15.2.1 (iPhone13,2)",274760,PL,Souk Eye,Gorillaz,The Now Now,spotify:track:4fjzDf54eBNOlW45mNe14U,None,None,None,...,NaN,trackdone,trackdone,False,False,0.0,NaN,False,2022-02-05,16:28:27

In [115]:
df = data[data['ts_date'].dt.year == 2021].copy()

In [117]:
import spotipy
sp = spotipy.Spotify(
        auth_manager=SpotifyClientCredentials(
            client_id=st.secrets["SPOTIPY_CLIENT_ID"],
            client_secret=st.secrets["SPOTIPY_CLIENT_SECRET"],
        )
    )

In [122]:
results = sp.search(q='artist:Taylor Swift', type='track')
if results['tracks']['items']:
    track = results['tracks']['items'][0]
    artist_id = track['artists'][0]['id']

    # Look up the artist to get the genre
    artist = sp.artist(artist_id)
    print(f"Artist Genres: {artist['genres']}")

Artist Genres: []

In [127]:
from lyricsgenius import Genius

In [128]:
GENIUS_ACCESS_TOKEN = "3O6Gergq8PJj06gtdB2sfrFwPdEMCgZzaN1rdjumu8Bwu8GVHZsYYgMzBsxUAxeF"

In [2]:
import pylast
API_KEY = "6965db6126f097d47caffafb327e5d40"
API_SECRET = "745589b948e9552a589aff3e8444f39a"

network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET)
track = network.get_track("Tate McRae", "Sports Car")
top_tags = track.get_top_tags()

if top_tags:
    print("Gatunki wg Last.fm:")
    for tag in top_tags[:5]:
        print(f"- {tag.item.get_name()}")
else:
    print("Brak tagów.")

Gatunki wg Last.fm:
- pop
- So Close to What
- rnb
- electropop
- dance-pop

In [3]:
artist = network.get_artist("Tate McRae")
similar = artist.get_similar(limit=10)
for item in similar:
    print(f"{item.item.name} - Podobieństwo: {item.match}")

Sabrina Carpenter - Podobieństwo: 1
Gracie Abrams - Podobieństwo: 0.940944
Nessa Barrett - Podobieństwo: 0.927675
Madison Beer - Podobieństwo: 0.926613
Zara Larsson - Podobieństwo: 0.885194
Ariana Grande - Podobieństwo: 0.733326
Reneé Rapp - Podobieństwo: 0.731078
Alessi Rose - Podobieństwo: 0.675123
Addison Rae - Podobieństwo: 0.630676
Camila Cabello - Podobieństwo: 0.596371

In [4]:
import musicbrainzngs

musicbrainzngs.set_useragent("Dashboard", "1.0", "aleksandramulewicz@gmail.com")

def get_artist_country(artist_name):
    try:
        result = musicbrainzngs.search_artists(artist=artist_name, limit=1)
        if result['artist-list']:
            artist_info = result['artist-list'][0]
            if 'area' in artist_info:
                return artist_info['area']['name']
            elif 'begin-area' in artist_info:
                return artist_info['begin-area']['name']

    except Exception as e:
        print(f"Błąd przy {artist_name}: {e}")
    return "Unknown"

print(f"Tate McRae jest z: {get_artist_country('Tate McRae')}")
print(f"Daft Punk jest z: {get_artist_country('Daft Punk')}")

Tate McRae jest z: Canada
Daft Punk jest z: France

In [5]:
import musicbrainzngs
import pandas as pd
import plotly.figure_factory as ff
from geopy.geocoders import Nominatim
import time
geolocator = Nominatim(user_agent="spotify_geo_mapper")
map_token = "pk.eyJ1IjoibXVsZXdpY3oiLCJhIjoiY205bDhkcWhtMDIzbjJrc2Y2NjEwd2hrdSJ9.nW_Ayi4_nvyuyfYMDGagrw"

In [ ]:
"you listened to x artists, we found y of them. See how it presents on the map"

In [13]:
df.to_csv("artysci_lokalizacje.csv", index=False, encoding="utf-8")